import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Stack;

/**
 * Handles Static Semantic Analysis for ImLang.
 * Requirement 1: Builds Symbol Table with factual attributes (values, sizes, types).
 * Requirement 2: Detects semantic errors (Redeclaration, Type mismatch, Scope violations).
 * Considers validation for load(), save(), filter(), crop(), Control Structures,
 * Math/Bounds checking, Logical/Arithmetic Operators, Loop Context, Unreachable Code,
 * and Self-Assignment.
 * @author John Seibert
 */
public class ImLangSemanticAnalyzer {

    private static List<Symbol> symbolTable;    // For Display (Phase 1)
    private static List<String> semanticErrors; // For Error Reporting (Phase 2)
    private static int currentScopeLevel;       // Shared tracker

    /**
     * Main entry point for Semantic Analysis.
     * @param tokens The list of tokens generated by the Lexer.
     * @return A list of semantic error messages (if any).
     */
    public static List<String> analyze(List<Token> tokens) {
        symbolTable = new ArrayList<>();
        semanticErrors = new ArrayList<>();
        currentScopeLevel = 0;

        // Phase 1: Build Table (Display Factual Attributes)
        buildSymbolTableForDisplay(tokens);

        // Phase 2: Logic Validation (Scope, Types, and Geometry)
        performSemanticAnalysis(tokens);

        return semanticErrors;
    }

    /**
     * Returns the formatted Symbol Table string for the GUI.
     */
    public static String getSymbolTableOutput() {
        if (symbolTable == null || symbolTable.isEmpty()) return "Symbol Table is empty.";

        StringBuilder sb = new StringBuilder("--- SYMBOL TABLE ---\n");
        sb.append(String.format("%-15s | %-15s | %-15s | %s\n", "NAME", "TYPE", "SCOPE CONTEXT", "ATTRIBUTES"));
        sb.append("-----------------------------------------------------------------------------------\n");

        for (Symbol s : symbolTable) {
            String scopeDisplay = s.scopeLabel() + " (L" + s.scopeLevel() + ")";
            sb.append(String.format("%-15s | %-15s | %-15s | %s\n",
                    s.name(), s.type(), scopeDisplay, s.attribute()));
        }
        return sb.toString();
    }

    // =============================================================
    // PHASE 1: DISPLAY & CONTEXT TRACKING (Factual Table Construction)
    // =============================================================
    private static void buildSymbolTableForDisplay(List<Token> tokens) {
        int scopeDepth = 0;
        Stack<String> scopeContextStack = new Stack<>();
        scopeContextStack.push("Global");
        String nextScopeType = "Block";

        for (int i = 0; i < tokens.size(); i++) {
            Token t = tokens.get(i);

            // 1. DETECT CONTROL STRUCTURES
            if (t.type() == TokenType.IF || t.type() == TokenType.WHILE ||
                    t.type() == TokenType.FOR || t.type() == TokenType.ELSE) {
                nextScopeType = "Block";
            }

            // 2. DETECT FUNCTION CONTEXT (Lookahead)
            else if (isType(t.type())) {
                int lookAhead = skipArraySyntax(tokens, i + 1);
                Token idToken = safeGet(tokens, lookAhead);
                if (idToken != null && idToken.type() == TokenType.ID) {
                    if (safeType(tokens, lookAhead + 1) == TokenType.LPAREN) {
                        nextScopeType = "Local";
                    }
                }
            }

            // 3. ENTERING SCOPE
            if (t.type() == TokenType.LBRACE) {
                scopeDepth++;
                scopeContextStack.push(nextScopeType);
                nextScopeType = "Block"; // Reset default
            }

            // 4. EXITING SCOPE
            else if (t.type() == TokenType.RBRACE) {
                if (scopeDepth > 0) {
                    scopeDepth--;
                    if (!scopeContextStack.isEmpty()) scopeContextStack.pop();
                }
            }

            // 5. RECORDING SYMBOLS
            else if (isType(t.type())) {
                String typeName = t.type().name().toLowerCase();
                String attribute = "variable"; // Default attribute

                int lookAhead = i + 1;

                // --- A. Handle Java-Style Array Syntax (int[] x) ---
                if (safeType(tokens, lookAhead) == TokenType.LBRACKET) {
                    typeName += "[]";
                    attribute = "array";

                    Token sizeToken = safeGet(tokens, lookAhead + 1);
                    if (sizeToken != null && sizeToken.type() == TokenType.NUM_LIT &&
                            safeType(tokens, lookAhead + 2) == TokenType.RBRACKET) {
                        if (t.type() == TokenType.REGION) attribute = "region-size=" + sizeToken.lexeme();
                        else attribute = "array-size=" + sizeToken.lexeme();
                        lookAhead += 3;
                    } else if (safeType(tokens, lookAhead + 1) == TokenType.RBRACKET) {
                        lookAhead += 2;
                    }
                }

                Token id = safeGet(tokens, lookAhead);
                if (id != null && id.type() == TokenType.ID) {

                    // --- B. Determine "Factual" Attribute & C-Style Arrays ---

                    // Case 1: Function Definition
                    if (safeType(tokens, lookAhead + 1) == TokenType.LPAREN) {
                        attribute = "function";
                    }
                    // Case 2: C-Style Array Syntax (int x[10])
                    else if (safeType(tokens, lookAhead + 1) == TokenType.LBRACKET) {
                        Token sizeToken = safeGet(tokens, lookAhead + 2);
                        if (!typeName.endsWith("[]")) {
                            typeName += "[]";
                        }
                        attribute = "array";

                        if (sizeToken != null && sizeToken.type() == TokenType.NUM_LIT) {
                            if (t.type() == TokenType.REGION) attribute = "region-size=" + sizeToken.lexeme();
                            else attribute = "array-size=" + sizeToken.lexeme();
                        }
                    }
                    // Case 3: Assignment / Initialization Values
                    else if (safeType(tokens, lookAhead + 1) == TokenType.ASSIGN) {
                        Token valueToken = safeGet(tokens, lookAhead + 2);

                        // Literal Values
                        if (valueToken != null && (valueToken.type() == TokenType.NUM_LIT ||
                                valueToken.type() == TokenType.STR_LIT || valueToken.type() == TokenType.BOOL)) {
                            attribute = "value=" + valueToken.lexeme();
                        }
                        // Array/Region Literals
                        else if (valueToken != null && valueToken.type() == TokenType.LBRACKET) {
                            int count = countElements(tokens, lookAhead + 2);
                            if (t.type() == TokenType.REGION) attribute = "region-size=" + count;
                            else attribute = "array-size=" + count;
                        }
                    }
                    // Case 4: Refined Classification
                    else if (attribute.equals("variable")) {
                        if (t.type() == TokenType.IMAGE) attribute = "image object";
                        else if (t.type() == TokenType.PIXEL) attribute = "pixel struct";
                        else if (t.type() == TokenType.MAT) attribute = "matrix";
                        else if (t.type() == TokenType.REGION) attribute = "region";
                    }

                    String currentContext = scopeContextStack.peek();
                    symbolTable.add(new Symbol(id.lexeme(), typeName, scopeDepth, currentContext, attribute));
                    i = lookAhead;
                }
            }
        }
    }

    // =============================================================
    // PHASE 2: SEMANTIC LOGIC (Validation & Error Checking)
    // =============================================================
    private static void performSemanticAnalysis(List<Token> tokens) {
        List<Symbol> activeSymbols = new ArrayList<>();
        currentScopeLevel = 0;

        // NEW: Track Loop Depth for Break/Continue validation
        Stack<Boolean> loopContextStack = new Stack<>();
        loopContextStack.push(false); // Base level is not a loop

        for (int i = 0; i < tokens.size(); i++) {
            Token t = tokens.get(i);

            // 1. SCOPE & LOOP CONTEXT MANAGEMENT
            if (t.type() == TokenType.LBRACE) {
                currentScopeLevel++;

                // Determine if this block is a loop body
                boolean isLoopBlock = isLoopHeader(tokens, i);
                if (isLoopBlock) {
                    loopContextStack.push(true);
                } else {
                    loopContextStack.push(loopContextStack.peek()); // Inherit state
                }
            }
            else if (t.type() == TokenType.RBRACE) {
                final int level = currentScopeLevel;
                activeSymbols.removeIf(s -> s.scopeLevel() == level);
                if (currentScopeLevel > 0) currentScopeLevel--;

                if (loopContextStack.size() > 1) loopContextStack.pop();
            }

            // 2. DECLARATIONS
            else if (isType(t.type())) {
                String typeName = t.type().name().toLowerCase();
                int lookAhead = skipArraySyntax(tokens, i + 1);

                // Java-Style Array Check
                if (lookAhead > i + 1) typeName += "[]";

                Token idToken = safeGet(tokens, lookAhead);

                // C-Style Array Check
                if (idToken != null && safeType(tokens, lookAhead + 1) == TokenType.LBRACKET) {
                    if (!typeName.endsWith("[]")) typeName += "[]";
                }

                if (idToken != null && idToken.type() == TokenType.ID) {
                    // Check if decl is in a loop header or func params to prevent leaks
                    int effectiveScopeLevel = currentScopeLevel;
                    if (isInHeaderContext(tokens, i)) {
                        effectiveScopeLevel++;
                    }

                    // Check for Re-declaration
                    boolean declaredInCurrentScope = false;
                    for (Symbol s : activeSymbols) {
                        if (s.name().equals(idToken.lexeme()) && s.scopeLevel() == effectiveScopeLevel) {
                            declaredInCurrentScope = true;
                            break;
                        }
                    }

                    if (declaredInCurrentScope) {
                        semanticErrors.add("Line " + idToken.line() + ": Re-declaration of '" +
                                idToken.lexeme() + "'. Variable already exists in this scope.");
                    } else {
                        // Add with valid effective scope
                        activeSymbols.add(new Symbol(idToken.lexeme(), typeName, effectiveScopeLevel, "Logic", "var"));
                    }

                    i = lookAhead;
                }
            }

            // 3. ASSIGNMENTS
            else if (t.type() == TokenType.ASSIGN) {
                if (i > 0 && tokens.get(i - 1).type() == TokenType.ID) {
                    Token lhsToken = tokens.get(i - 1);
                    Symbol lhsSym = findSymbol(activeSymbols, lhsToken.lexeme());
                    Token rhsToken = safeGet(tokens, i + 1);

                    // NEW: Self-Assignment Check (x = x)
                    if (rhsToken != null && rhsToken.type() == TokenType.ID && rhsToken.lexeme().equals(lhsToken.lexeme())) {
                        semanticErrors.add("Line " + t.line() + ": Self-assignment of variable '" + lhsToken.lexeme() + "' has no effect.");
                    }

                    if (lhsSym == null) {
                        semanticErrors.add("Line " + lhsToken.line() + ": Undeclared identifier '" + lhsToken.lexeme() + "'. ");
                    } else if (rhsToken != null) {
                        checkTypeMismatch(lhsSym, rhsToken, activeSymbols);

                        // --- FIX: Specific Geometry Validation Calls ---

                        // Region Geometry Validation
                        if (lhsSym.type().startsWith("region") && rhsToken.type() == TokenType.LBRACKET) {
                            validateRegionGeometry(tokens, i + 1, lhsToken.line());
                        }

                        // Pixel Geometry Validation
                        if (lhsSym.type().startsWith("pixel") && rhsToken.type() == TokenType.LBRACKET) {
                            validatePixelGeometry(tokens, i + 1, lhsToken.line());
                        }

                        // Matrix Geometry Validation
                        if (lhsSym.type().equals("mat") && rhsToken.type() == TokenType.LBRACKET) {
                            validateMatrixGeometry(tokens, i + 1, lhsToken.line());
                        }
                    }
                }
            }

            // 4. IDENTIFIER USAGE (Rule D: Undeclared / Scope Violation)
            else if (t.type() == TokenType.ID) {
                boolean prevWasBracket = (i > 0 && tokens.get(i-1).type() == TokenType.RBRACKET); // e.g. arr[x]
                boolean isDecl = (i > 0 && isType(tokens.get(i-1).type())); // e.g. int x
                boolean isLHS  = (safeType(tokens, i+1) == TokenType.ASSIGN); // e.g. x = 5

                // If it's not a declaration and not the Left Hand Side of an assignment
                if (!isDecl && !isLHS && !prevWasBracket) {
                    if (findSymbol(activeSymbols, t.lexeme()) == null) {
                        semanticErrors.add("Line " + t.line() + ": Undeclared identifier '" + t.lexeme() + "'.");
                    }
                }
            }

            // 5. BUILT-IN FUNCTION VALIDATION
            else if (t.type() == TokenType.LOAD) {
                validateLoadCall(tokens, i, t.line(), activeSymbols);
            }
            else if (t.type() == TokenType.SAVE) {
                validateSaveCall(tokens, i, t.line(), activeSymbols);
            }
            else if (t.type() == TokenType.FILTER) {
                validateFilterCall(tokens, i, t.line(), activeSymbols);
            }
            else if (t.type() == TokenType.CROP) {
                validateCropCall(tokens, i, t.line(), activeSymbols);
            }

            // 6. CONTROL STRUCTURE VALIDATION
            else if (t.type() == TokenType.IF || t.type() == TokenType.WHILE) {
                validateCondition(tokens, i, t.line(), activeSymbols);
            }
            else if (t.type() == TokenType.FOR) {
                validateForLoop(tokens, i, t.line(), activeSymbols);
            }

            // 7. MATH / LOGIC VALIDATION
            else if (t.type() == TokenType.DIV || t.type() == TokenType.MOD) {
                validateMathOp(tokens, i, t.line(), activeSymbols);
            }
            else if (t.type() == TokenType.AND || t.type() == TokenType.OR) {
                validateLogicalOp(tokens, i, t.line(), activeSymbols);
            }
            else if (t.type() == TokenType.PLUS || t.type() == TokenType.MINUS || t.type() == TokenType.MULT) {
                validateArithmeticOp(tokens, i, t.line(), activeSymbols);
            }

            // 8. ARRAY INDEX CHECKS
            else if (t.type() == TokenType.LBRACKET) {
                Token indexToken = safeGet(tokens, i + 1);
                Token arrayId = safeGet(tokens, i - 1); // Get the ID before the bracket
                if (indexToken != null) checkArrayIndex(arrayId, indexToken, activeSymbols);
            }

            // 9. BREAK / CONTINUE VALIDATION
            else if (t.type() == TokenType.BREAK || t.type() == TokenType.CONTINUE) {
                if (!loopContextStack.peek()) {
                    semanticErrors.add("Line " + t.line() + ": " + t.type() + " statement must be inside a loop.");
                }

                // 10. UNREACHABLE CODE CHECK
                // If statements follow break/continue in the same block immediately
                if (i + 2 < tokens.size()) {
                    Token next = tokens.get(i + 2); // Skip SEMI
                    // If next is not a closing brace or EOF or ELSE, code is unreachable
                    if (next.type() != TokenType.RBRACE && next.type() != TokenType.EOF && next.type() != TokenType.ELSE) {
                        semanticErrors.add("Line " + next.line() + ": Unreachable code detected after " + t.type() + ".");
                    }
                }
            }
        }
    }

    // =============================================================
    // HELPER METHODS
    // =============================================================

    /**
     * Checks if the LBRACE at the given index belongs to a loop (FOR/WHILE).
     */
    private static boolean isLoopHeader(List<Token> tokens, int braceIndex) {
        if (braceIndex > 0 && safeType(tokens, braceIndex - 1) == TokenType.RPAREN) {
            int balance = 0;
            for (int k = braceIndex - 1; k >= 0; k--) {
                if (tokens.get(k).type() == TokenType.RPAREN) balance++;
                else if (tokens.get(k).type() == TokenType.LPAREN) balance--;

                if (balance == 0) {
                    if (k > 0) {
                        TokenType prev = tokens.get(k - 1).type();
                        return (prev == TokenType.WHILE || prev == TokenType.FOR);
                    }
                    break;
                }
            }
        }
        return false;
    }

    /**
     * Checks if the current declaration is inside a control structure header or function parameter list.
     * Prevents variables declared in "for(...)" or "func(...)" from leaking into the parent scope.
     */
    private static boolean isInHeaderContext(List<Token> tokens, int typeIndex) {
        int ptr = typeIndex - 1;
        while (ptr >= 0) {
            Token t = tokens.get(ptr);

            // Optimization: Stop at statement boundaries
            if (t.type() == TokenType.LBRACE || t.type() == TokenType.SEMI || t.type() == TokenType.RBRACE) {
                return false;
            }

            if (t.type() == TokenType.LPAREN) {
                if (ptr > 0) {
                    Token prev = tokens.get(ptr - 1);
                    // Loop Headers
                    if (prev.type() == TokenType.FOR || prev.type() == TokenType.WHILE || prev.type() == TokenType.IF) {
                        return true;
                    }
                    // Function Parameters (TYPE ID LPAREN)
                    if (prev.type() == TokenType.ID) {
                        return ptr > 1 && isType(tokens.get(ptr - 2).type());
                    }
                }
                return false;
            }
            ptr--;
        }
        return false;
    }

    /**
     * Validates Arithmetic Operators (+, -, *).
     * Ensures operands are numeric (int/float) or String (for + only).
     */
    private static void validateArithmeticOp(List<Token> tokens, int opIndex, int lineNum, List<Symbol> activeSymbols) {
        Token lhs = safeGet(tokens, opIndex - 1);
        Token rhs = safeGet(tokens, opIndex + 1);
        TokenType op = tokens.get(opIndex).type();

        // 1. Boolean Operand Check (General Arithmetic)
        if (lhs != null && (lhs.type() == TokenType.BOOL || (lhs.type() == TokenType.ID && isVarType(lhs, "bool", activeSymbols)))) {
            semanticErrors.add("Line " + lineNum + ": Arithmetic operator cannot be applied to BOOL operand.");
        }
        if (rhs != null && (rhs.type() == TokenType.BOOL || (rhs.type() == TokenType.ID && isVarType(rhs, "bool", activeSymbols)))) {
            semanticErrors.add("Line " + lineNum + ": Arithmetic operator cannot be applied to BOOL operand.");
        }

        // 2. String Concatenation Safety (Only + allows strings)
        boolean lhsIsString = (lhs != null && (lhs.type() == TokenType.STR_LIT || (lhs.type() == TokenType.ID && isVarType(lhs, "string", activeSymbols))));
        boolean rhsIsString = (rhs != null && (rhs.type() == TokenType.STR_LIT || (rhs.type() == TokenType.ID && isVarType(rhs, "string", activeSymbols))));

        if (lhsIsString || rhsIsString) {
            if (op != TokenType.PLUS) {
                semanticErrors.add("Line " + lineNum + ": Operator " + op + " cannot be applied to STRING operands.");
            } else if (!lhsIsString || !rhsIsString) {
                // If using +, both must be strings to be valid concat in ImLang (simplified rule)
                semanticErrors.add("Line " + lineNum + ": String concatenation requires both operands to be STRING.");
            }
        }
    }

    /**
     * Validates Logical Operators (&&, ||).
     * Ensures operands are BOOLEAN.
     */
    private static void validateLogicalOp(List<Token> tokens, int opIndex, int lineNum, List<Symbol> activeSymbols) {
        Token lhs = safeGet(tokens, opIndex - 1);
        Token rhs = safeGet(tokens, opIndex + 1);

        // Check LHS
        boolean lhsValid = false;
        if (lhs != null) {
            if (lhs.type() == TokenType.BOOL) lhsValid = true;
            else if (lhs.type() == TokenType.ID && isVarType(lhs, "bool", activeSymbols)) lhsValid = true;
            else if (lhs.type() == TokenType.RPAREN) lhsValid = true; // Assume complex expression
        }

        // Check RHS
        boolean rhsValid = false;
        if (rhs != null) {
            if (rhs.type() == TokenType.BOOL) rhsValid = true;
            else if (rhs.type() == TokenType.ID && isVarType(rhs, "bool", activeSymbols)) rhsValid = true;
            else if (rhs.type() == TokenType.LPAREN || rhs.type() == TokenType.NOT) rhsValid = true;
        }

        if (!lhsValid && lhs != null && (lhs.type() == TokenType.NUM_LIT || lhs.type() == TokenType.STR_LIT)) {
            semanticErrors.add("Line " + lineNum + ": Logical operator requires BOOL operands (found " + lhs.type() + ").");
        }
        if (!rhsValid && rhs != null && (rhs.type() == TokenType.NUM_LIT || rhs.type() == TokenType.STR_LIT)) {
            semanticErrors.add("Line " + lineNum + ": Logical operator requires BOOL operands (found " + rhs.type() + ").");
        }
    }

    private static boolean isVarType(Token t, String expected, List<Symbol> syms) {
        Symbol s = findSymbol(syms, t.lexeme());
        return (s != null && s.type().equals(expected));
    }

    /**
     * Validates Math Operators.
     * 1. Detects Division by Zero (Literal).
     * 2. Detects Modulo usage on Floats.
     */
    private static void validateMathOp(List<Token> tokens, int opIndex, int lineNum, List<Symbol> activeSymbols) {
        Token op = tokens.get(opIndex);
        Token rhs = safeGet(tokens, opIndex + 1);
        Token lhs = safeGet(tokens, opIndex - 1);

        // Check 1: Division by Zero
        if (op.type() == TokenType.DIV) {
            if (rhs != null && rhs.type() == TokenType.NUM_LIT) {
                if (rhs.lexeme().equals("0") || rhs.lexeme().equals("0.0")) {
                    semanticErrors.add("Line " + lineNum + ": Division by zero is undefined.");
                }
            }
        }

        // Check 2: Modulo Operand Types (Must be INT)
        if (op.type() == TokenType.MOD) {
            boolean lhsIsFloat = (lhs != null && lhs.type() == TokenType.NUM_LIT && lhs.lexeme().contains("."));
            boolean rhsIsFloat = (rhs != null && rhs.type() == TokenType.NUM_LIT && rhs.lexeme().contains("."));

            // Check variables
            if (lhs != null && lhs.type() == TokenType.ID) {
                Symbol s = findSymbol(activeSymbols, lhs.lexeme());
                if (s != null && s.type().equals("float")) lhsIsFloat = true;
            }
            if (rhs != null && rhs.type() == TokenType.ID) {
                Symbol s = findSymbol(activeSymbols, rhs.lexeme());
                if (s != null && s.type().equals("float")) rhsIsFloat = true;
            }

            if (lhsIsFloat || rhsIsFloat) {
                semanticErrors.add("Line " + lineNum + ": Modulo operator (%) is only valid for INT operands.");
            }
        }
    }

    /**
     * Validates Boolean Conditions in IF and WHILE statements.
     */
    private static void validateCondition(List<Token> tokens, int startIndex, int lineNum, List<Symbol> activeSymbols) {
        Token lparen = safeGet(tokens, startIndex + 1);
        if (lparen == null || lparen.type() != TokenType.LPAREN) return; // Parser handles this syntax error

        int rparenIndex = -1;
        boolean hasRelationalOp = false;
        boolean hasBooleanTerm = false;

        // Scan inside parenthesis
        for (int k = startIndex + 2; k < tokens.size(); k++) {
            Token t = tokens.get(k);
            if (t.type() == TokenType.RPAREN) {
                rparenIndex = k;
                break;
            }
            // Check for Boolean indicators
            if (t.type() == TokenType.BOOL) hasBooleanTerm = true;
            if (t.type() == TokenType.EQ || t.type() == TokenType.NEQ || t.type() == TokenType.LT ||
                    t.type() == TokenType.GT || t.type() == TokenType.LTE || t.type() == TokenType.GTE) {
                hasRelationalOp = true;
            }
            // Check variables
            if (t.type() == TokenType.ID) {
                Symbol s = findSymbol(activeSymbols, t.lexeme());
                if (s != null && s.type().equals("bool")) hasBooleanTerm = true;
            }
        }

        // Simplistic Semantic Check:
        if (rparenIndex > startIndex + 2) {
            // Case: Single Token check (e.g. if(x))
            if (!hasRelationalOp && !hasBooleanTerm) {
                // If we didn't find an explicit boolean or op, check the single token content
                Token inner = tokens.get(startIndex + 2);
                boolean validSingle = false;
                if (inner.type() == TokenType.ID) {
                    Symbol s = findSymbol(activeSymbols, inner.lexeme());
                    if (s != null && s.type().equals("bool")) validSingle = true;
                } else if (inner.type() == TokenType.BOOL) {
                    validSingle = true;
                }

                if (!validSingle) {
                    semanticErrors.add("Line " + lineNum + ": Condition must be a BOOLEAN expression.");
                }
            }
        }
    }

    /**
     * Validates FOR loop structure: for(i=start..end).
     * Requirement: start and end must be integers.
     */
    private static void validateForLoop(List<Token> tokens, int startIndex, int lineNum, List<Symbol> activeSymbols) {
        // Look for the RANGE operator (..) inside the header
        int rangeIndex = -1;
        int rparenIndex = -1;

        for (int k = startIndex + 1; k < tokens.size(); k++) {
            if (tokens.get(k).type() == TokenType.RBRACE || tokens.get(k).type() == TokenType.LBRACE) break; // Safety
            if (tokens.get(k).type() == TokenType.RANGE) rangeIndex = k;
            if (tokens.get(k).type() == TokenType.RPAREN) {
                rparenIndex = k;
                break;
            }
        }

        if (rangeIndex == -1) return; // Parser likely caught missing range, or it's a malformed loop

        // Check Start (Left of Range)
        Token startTok = safeGet(tokens, rangeIndex - 1);
        if (startTok != null) {
            if (!isValidType(startTok, "int", activeSymbols)) {
                semanticErrors.add("Line " + lineNum + ": For-loop start value must be INT.");
            }
        }

        // Check End (Right of Range)
        Token endTok = safeGet(tokens, rangeIndex + 1);
        if (endTok != null) {
            if (!isValidType(endTok, "int", activeSymbols)) {
                semanticErrors.add("Line " + lineNum + ": For-loop end value must be INT.");
            }
        }

        // Logic Check: Start <= End (if both are literals)
        if (startTok != null && endTok != null &&
                startTok.type() == TokenType.NUM_LIT && endTok.type() == TokenType.NUM_LIT) {
            try {
                int sVal = Integer.parseInt(startTok.lexeme());
                int eVal = Integer.parseInt(endTok.lexeme());
                if (sVal > eVal) {
                    semanticErrors.add("Line " + lineNum + ": For-loop range invalid. Start (" + sVal + ") > End (" + eVal + ").");
                }
            } catch (NumberFormatException e) { /* Ignore */ }
        }
    }

    /**
     * Validates load() function.
     * Requirement: Must have exactly 1 argument, and it must be a STRING.
     */
    private static void validateLoadCall(List<Token> tokens, int funcIndex, int lineNum, List<Symbol> activeSymbols) {
        int argIndex = funcIndex + 2; // Skip NAME and LPAREN
        Token arg = safeGet(tokens, argIndex);

        if (arg == null || arg.type() == TokenType.RPAREN) {
            semanticErrors.add("Line " + lineNum + ": load() requires 1 argument (string path).");
            return;
        }

        if (!isValidType(arg, "string", activeSymbols)) {
            semanticErrors.add("Line " + lineNum + ": load() argument 1 must be a STRING.");
        }

        if (safeType(tokens, argIndex + 1) != TokenType.RPAREN) {
            semanticErrors.add("Line " + lineNum + ": load() expects exactly 1 argument.");
        }
    }

    /**
     * Validates save() function.
     * Requirement: save(image, string location). Order Matters.
     */
    private static void validateSaveCall(List<Token> tokens, int funcIndex, int lineNum, List<Symbol> activeSymbols) {
        int arg1Index = funcIndex + 2;
        Token arg1 = safeGet(tokens, arg1Index);

        if (arg1 == null || arg1.type() == TokenType.RPAREN) {
            semanticErrors.add("Line " + lineNum + ": save() requires 2 arguments (image, string).");
            return;
        }

        if (!isValidType(arg1, "image", activeSymbols)) {
            semanticErrors.add("Line " + lineNum + ": save() argument 1 must be type IMAGE.");
        }

        if (safeType(tokens, arg1Index + 1) != TokenType.COMMA) {
            semanticErrors.add("Line " + lineNum + ": save() expects a comma between arguments.");
            return;
        }

        Token arg2 = safeGet(tokens, arg1Index + 2);
        if (arg2 == null || !isValidType(arg2, "string", activeSymbols)) {
            semanticErrors.add("Line " + lineNum + ": save() argument 2 must be type STRING (path).");
        }

        if (safeType(tokens, arg1Index + 3) != TokenType.RPAREN) {
            semanticErrors.add("Line " + lineNum + ": save() expects exactly 2 arguments.");
        }
    }

    /**
     * Validates filter() function.
     * Requirement: filter(image, mat). Order Matters.
     */
    private static void validateFilterCall(List<Token> tokens, int funcIndex, int lineNum, List<Symbol> activeSymbols) {
        int arg1Index = funcIndex + 2;
        Token arg1 = safeGet(tokens, arg1Index);

        if (arg1 == null || arg1.type() == TokenType.RPAREN) {
            semanticErrors.add("Line " + lineNum + ": filter() requires 2 arguments (image, mat).");
            return;
        }

        if (!isValidType(arg1, "image", activeSymbols)) {
            semanticErrors.add("Line " + lineNum + ": filter() argument 1 must be type IMAGE.");
        }

        if (safeType(tokens, arg1Index + 1) != TokenType.COMMA) {
            semanticErrors.add("Line " + lineNum + ": filter() expects a comma between arguments.");
            return;
        }

        Token arg2 = safeGet(tokens, arg1Index + 2);
        if (arg2 == null || !isValidType(arg2, "mat", activeSymbols)) {
            semanticErrors.add("Line " + lineNum + ": filter() argument 2 must be type MAT (matrix).");
        }

        if (safeType(tokens, arg1Index + 3) != TokenType.RPAREN) {
            semanticErrors.add("Line " + lineNum + ": filter() expects exactly 2 arguments.");
        }
    }

    /**
     * Validates crop() function.
     * Supports Multiple Signatures:
     * 1. crop(image, int, int, int, int) -> 5 args (Explicit)
     * 2. crop(image, [int, int, int, int]) -> 2 args (Literal Array)
     * 3. crop(image, region/mat/int[]) -> 2 args (Variable)
     */
    private static void validateCropCall(List<Token> tokens, int funcIndex, int lineNum, List<Symbol> activeSymbols) {
        int arg1Index = funcIndex + 2;
        Token arg1 = safeGet(tokens, arg1Index);

        // Arg 1: Always IMAGE
        if (arg1 == null || !isValidType(arg1, "image", activeSymbols)) {
            semanticErrors.add("Line " + lineNum + ": crop() argument 1 must be type IMAGE.");
            return;
        }

        if (safeType(tokens, arg1Index + 1) != TokenType.COMMA) {
            semanticErrors.add("Line " + lineNum + ": crop() expects comma after first argument.");
            return;
        }

        int arg2Index = arg1Index + 2;
        Token arg2 = safeGet(tokens, arg2Index);

        if (arg2 == null) return;

        // PATH A: Literal Array Syntax -> crop(im, [10,10,100,100])
        if (arg2.type() == TokenType.LBRACKET) {
            List<Integer> vals = getIntegers(tokens, arg2Index);
            if (vals.size() != 4) {
                semanticErrors.add("Line " + lineNum + ": crop() array literal must have exactly 4 integers [x1, y1, x2, y2].");
            }
            // Verify closing syntax
            int expectedRBrace = skipArraySyntax(tokens, arg2Index);
            if (safeType(tokens, expectedRBrace) != TokenType.RPAREN) {
                semanticErrors.add("Line " + lineNum + ": Malformed crop() call (brackets).");
            }
        }

        // PATH B: Variable (Region, Mat, or Int[]) -> crop(im, r)
        else if (arg2.type() == TokenType.ID) {
            Symbol s = findSymbol(activeSymbols, arg2.lexeme());
            boolean validVar = false;
            if (s != null) {
                String t = s.type();
                if (t.equals("region") || t.equals("mat") || t.endsWith("[]")) {
                    validVar = true;
                }
            }
            if (validVar) {
                if (safeType(tokens, arg2Index + 1) != TokenType.RPAREN) {
                    semanticErrors.add("Line " + lineNum + ": crop() with variable expects 2 arguments.");
                }
            } else {
                // Not a valid variable? Maybe it's Signature C (5 Integers) starting with an ID?
                // Let's assume user tried 5-arg version but passed an int variable.
                // Fallthrough to Path C.
            }
        }

        // PATH C: 5-Argument Syntax -> crop(im, x1, y1, x2, y2)
        // We check if we have 4 more int-compatible tokens separated by commas
        if (arg2.type() == TokenType.NUM_LIT || (arg2.type() == TokenType.ID && isValidType(arg2, "int", activeSymbols))) {
            // Check args 3, 4, 5
            int currentIdx = arg2Index;
            for(int k=0; k<3; k++) {
                if (safeType(tokens, currentIdx + 1) != TokenType.COMMA) {
                    // Only error if we are sure it's not the 2-arg variable path
                    if (k==0 && arg2.type() == TokenType.ID) return; // Might be arg mismatch on Path B

                    semanticErrors.add("Line " + lineNum + ": crop() 5-arg syntax expects 4 integers separated by commas.");
                    return;
                }
                currentIdx += 2;
                Token nextArg = safeGet(tokens, currentIdx);
                if (nextArg == null || (!isValidType(nextArg, "int", activeSymbols) && nextArg.type() != TokenType.NUM_LIT)) {
                    semanticErrors.add("Line " + lineNum + ": crop() coordinate argument " + (k+3) + " must be INT.");
                }
            }
            if (safeType(tokens, currentIdx + 1) != TokenType.RPAREN) {
                semanticErrors.add("Line " + lineNum + ": crop() 5-arg syntax expects exactly 5 arguments.");
            }
        }
    }

    /**
     * Helper to check if a token matches a specific type (either literal or variable).
     */
    private static boolean isValidType(Token t, String expectedType, List<Symbol> activeSymbols) {
        // 1. Check Literals
        if (expectedType.equals("string") && t.type() == TokenType.STR_LIT) return true;
        if (expectedType.equals("int") && t.type() == TokenType.NUM_LIT && !t.lexeme().contains(".")) return true;

        // 2. Check Variables
        if (t.type() == TokenType.ID) {
            Symbol s = findSymbol(activeSymbols, t.lexeme());
            if (s != null && s.type().equals(expectedType)) return true;
        }
        return false;
    }

    /**
     * Validates that a Pixel initialization array has exactly 4 elements.
     * @param tokens The full token list.
     * @param bracketIndex The index of the opening bracket [
     * @param lineNum The line number for error reporting.
     */
    private static void validatePixelGeometry(List<Token> tokens, int bracketIndex, int lineNum) {
        List<Integer> vals = getIntegers(tokens, bracketIndex);
        if (vals.size() != 4) {
            semanticErrors.add("Line " + lineNum + ": Invalid Pixel. Expected 4 values (RGBA), found " + vals.size() + ".");
        }

        // Check for negative values
        for (int val : vals) {
            if (val < 0) {
                semanticErrors.add("Line " + lineNum + ": Invalid Pixel. Value cannot be negative: " + val);
                return;
            }
        }
    }

    /**
     * Validates Matrix geometry (Consistent column count across all rows).
     * @param tokens The full token list.
     * @param bracketIndex The index of the opening bracket [
     * @param lineNum The line number for error reporting.
     */
    private static void validateMatrixGeometry(List<Token> tokens, int bracketIndex, int lineNum) {
        int idx = bracketIndex + 1;
        int currentRowCols = 0;
        int expectedCols = -1; // Determined by the first row
        int rowCount = 0;

        while (idx < tokens.size() && tokens.get(idx).type() != TokenType.RBRACKET) {
            Token t = tokens.get(idx);

            // If we hit a semicolon, the row is finished.
            if (t.type() == TokenType.SEMI) {
                if (rowCount == 0) {
                    expectedCols = currentRowCols;
                } else {
                    if (currentRowCols != expectedCols) {
                        semanticErrors.add("Line " + lineNum + ": Invalid Matrix. Row " + (rowCount + 1) +
                                " has " + currentRowCols + " columns, expected " + expectedCols + ".");
                        return;
                    }
                }
                rowCount++;
                currentRowCols = 0;
            }
            // If we hit a number or an ID, count it as a column
            else if (t.type() == TokenType.NUM_LIT || t.type() == TokenType.ID) {
                currentRowCols++;
            }
            // Ignore commas and minus signs (minus signs are just part of the next number)
            idx++;
        }

        // Check the final row (which doesn't end with a semicolon)
        if (currentRowCols > 0) {
            if (expectedCols != -1 && currentRowCols != expectedCols) {
                semanticErrors.add("Line " + lineNum + ": Invalid Matrix. Row " + (rowCount + 1) +
                        " has " + currentRowCols + " columns, expected " + expectedCols + ".");
            }
        }
    }


    /**
     * Validates Region geometry (Even count, Min 3 points, Non-collinear).
     * @param tokens The full token list.
     * @param bracketIndex The index of the opening bracket [
     * @param lineNum The line number for error reporting.
     */
    private static void validateRegionGeometry(List<Token> tokens, int bracketIndex, int lineNum) {
        List<Integer> coords = getIntegers(tokens, bracketIndex);
        int size = coords.size();

        // 1. Even number of points check
        if (size % 2 != 0) {
            semanticErrors.add("Line " + lineNum + ": Invalid Region. Coordinate count (" + size + ") must be EVEN.");
            return;
        }

        // 2. Minimum points check
        if (size < 6) {
            semanticErrors.add("Line " + lineNum + ": Invalid Region. Min 3 points (6 values) required.");
            return;
        }

        // 3. Collinearity Check (Area Calculation)
        List<Integer> xCoords = new ArrayList<>();
        List<Integer> yCoords = new ArrayList<>();
        Set<String> distinctPoints = new HashSet<>();

        for (int k = 0; k < size; k += 2) {
            int x = coords.get(k), y = coords.get(k+1);
            String pt = "(" + x + "," + y + ")";
            if (distinctPoints.contains(pt)) semanticErrors.add("Line " + lineNum + ": Duplicate vertex " + pt + ".");
            distinctPoints.add(pt);
            xCoords.add(x); yCoords.add(y);
        }

        long sum1 = 0, sum2 = 0;
        int n = xCoords.size();
        for (int k = 0; k < n - 1; k++) {
            sum1 += (long) xCoords.get(k) * yCoords.get(k+1);
            sum2 += (long) yCoords.get(k) * xCoords.get(k+1);
        }
        sum1 += (long) xCoords.get(n-1) * yCoords.getFirst();
        sum2 += (long) yCoords.get(n-1) * xCoords.getFirst();

        if (Math.abs(sum1 - sum2) == 0) {
            semanticErrors.add("Line " + lineNum + ": Invalid Region. Vertices are collinear (Area 0).");
        }
    }

    /**
     * Parses integer literals from an array bracket structure.
     * Handles negative numbers.
     */
    private static List<Integer> getIntegers(List<Token> tokens, int bracketIndex) {
        List<Integer> coords = new ArrayList<>();
        int idx = bracketIndex + 1;
        while (idx < tokens.size() && tokens.get(idx).type() != TokenType.RBRACKET) {
            Token t = tokens.get(idx);

            // Handle negative numbers (MINUS followed by NUM_LIT)
            boolean isNegative = false;
            if (t.type() == TokenType.MINUS) {
                isNegative = true;
                idx++;
                if (idx < tokens.size()) t = tokens.get(idx);
            }

            if (t.type() == TokenType.NUM_LIT) {
                if (!t.lexeme().contains(".")) {
                    try {
                        int val = Integer.parseInt(t.lexeme());
                        if (isNegative) val = -val;
                        coords.add(val);
                    } catch (NumberFormatException e) { /* Ignore */ }
                }
            }
            idx++;
        }
        return coords;
    }

    private static int countElements(List<Token> tokens, int bracketIndex) {
        int count = 0;
        int idx = bracketIndex + 1;
        while (idx < tokens.size() && tokens.get(idx).type() != TokenType.RBRACKET) {
            if (tokens.get(idx).type() == TokenType.NUM_LIT || tokens.get(idx).type() == TokenType.ID) {
                count++;
            }
            idx++;
        }
        return count;
    }

    private static int skipArraySyntax(List<Token> tokens, int start) {
        int idx = start;
        if (safeType(tokens, idx) == TokenType.LBRACKET) {
            if (safeType(tokens, idx + 1) == TokenType.NUM_LIT && safeType(tokens, idx + 2) == TokenType.RBRACKET) return idx + 3;
            if (safeType(tokens, idx + 1) == TokenType.RBRACKET) return idx + 2;
        }
        return idx;
    }

    private static void checkTypeMismatch(Symbol lhs, Token rhs, List<Symbol> activeSymbols) {
        String lhsType = lhs.type();
        boolean lhsIsArray = lhsType.endsWith("[]");

        // NEW: Check for Void Function Assignments
        if (rhs.type() == TokenType.SAVE || rhs.type() == TokenType.FILTER) {
            semanticErrors.add("Line " + rhs.line() + ": Cannot assign result of void function (" + rhs.lexeme() + ") to variable.");
            return;
        }

        // 1. RHS is Literal
        if (rhs.type() == TokenType.NUM_LIT) {
            if (lhsIsArray) {
                semanticErrors.add("Line " + rhs.line() + ": Type Mismatch. Cannot assign scalar NUMBER to Array '" + lhsType + "'. ");
                return;
            }
            if (lhsType.equals("int") && rhs.lexeme().contains("."))
                semanticErrors.add("Line " + rhs.line() + ": Cannot assign FLOAT to INT.");
            else if (!lhsType.equals("int") && !lhsType.equals("float"))
                semanticErrors.add("Line " + rhs.line() + ": Cannot assign number to " + lhsType.toUpperCase() + ".");
        } else if (rhs.type() == TokenType.STR_LIT) {
            if (lhsIsArray) semanticErrors.add("Line " + rhs.line() + ": Type Mismatch. Cannot assign scalar STRING to Array '" + lhsType + "'.");
            else if (!lhsType.equals("string")) semanticErrors.add("Line " + rhs.line() + ": Cannot assign STRING to " + lhsType + ".");
        } else if (rhs.type() == TokenType.BOOL) {
            if (lhsIsArray) semanticErrors.add("Line " + rhs.line() + ": Type Mismatch. Cannot assign scalar BOOL to Array '" + lhsType + "'.");
            else if (!lhsType.equals("bool")) semanticErrors.add("Line " + rhs.line() + ": Cannot assign BOOL to " + lhsType + ".");
        }

        // ---------------------------------------------------------
        // NEW CLAUSE: Handle Array Literals (e.g. [1, 2])
        // ---------------------------------------------------------
        else if (rhs.type() == TokenType.LBRACKET) {
            // Special types in ImLang (region, pixel, mat) use [...] syntax even though they aren't "arrays"
            boolean isSpecialType = lhsType.equals("region") || lhsType.equals("pixel") || lhsType.equals("mat");

            // If it's not an array AND not one of the special types, it's an error.
            if (!lhsIsArray && !isSpecialType) {
                semanticErrors.add("Line " + rhs.line() + ": Type Mismatch. Cannot assign Array Literal to Primitive '" + lhsType + "'.");
            }
        }

        // 2. RHS is Variable
        else if (rhs.type() == TokenType.ID) {
            Symbol rhsSym = findSymbol(activeSymbols, rhs.lexeme());
            if (rhsSym != null) {
                String rhsType = rhsSym.type();
                boolean rhsIsArray = rhsType.endsWith("[]");

                if (lhsIsArray && !rhsIsArray) {
                    semanticErrors.add("Line " + rhs.line() + ": Type Mismatch. Cannot assign Primitive '" + rhsType + "' to Array '" + lhsType + "'.");
                    return;
                }
                if (!lhsIsArray && rhsIsArray) {
                    semanticErrors.add("Line " + rhs.line() + ": Type Mismatch. Cannot assign Array '" + rhsType + "' to Primitive '" + lhsType + "'.");
                    return;
                }
                if (!lhsIsArray && lhsType.equals("float") && rhsType.equals("int")) return; // Implicit cast allowed

                if (!lhsType.equals(rhsType)) {
                    semanticErrors.add("Line " + rhs.line() + ": Cannot assign " + rhsType + " to " + lhsType + ".");
                }
            }
        }
    }

    private static void checkArrayIndex(Token arrayId, Token indexToken, List<Symbol> activeSymbols) {
        if (indexToken.type() == TokenType.STR_LIT) semanticErrors.add("Line " + indexToken.line() + ": Index cannot be STRING. ");
        else if (indexToken.type() == TokenType.NUM_LIT) {
            if (indexToken.lexeme().contains(".")) {
                semanticErrors.add("Line " + indexToken.line() + ": Index cannot be FLOAT. ");
            } else {
                // Static Bounds Checking
                if (arrayId != null && arrayId.type() == TokenType.ID) {
                    Symbol sym = findSymbol(activeSymbols, arrayId.lexeme());
                    if (sym != null) {
                        String attr = sym.attribute(); // e.g., "array-size=10"
                        if (attr.startsWith("array-size=")) {
                            try {
                                int size = Integer.parseInt(attr.substring(11));
                                int indexVal = Integer.parseInt(indexToken.lexeme());
                                if (indexVal < 0 || indexVal >= size) {
                                    semanticErrors.add("Line " + indexToken.line() + ": Array index out of bounds. Index " + indexVal + ", Size " + size + ".");
                                }
                            } catch (NumberFormatException e) { /* Ignore */ }
                        }
                    }
                }
            }
        }
        else if (indexToken.type() == TokenType.BOOL) semanticErrors.add("Line " + indexToken.line() + ": Index cannot be BOOL.");
        else if (indexToken.type() == TokenType.ID) {
            Symbol sym = findSymbol(activeSymbols, indexToken.lexeme());
            if (sym != null && !sym.type().equals("int")) semanticErrors.add("Line " + indexToken.line() + ": Index must be INT.");
        }
    }

    private static Symbol findSymbol(List<Symbol> symbols, String name) {
        // Search backwards to find the most recent declaration (Rule D: Nearest Scope)
        for (int i = symbols.size() - 1; i >= 0; i--) if (symbols.get(i).name().equals(name)) return symbols.get(i);
        return null;
    }

    private static boolean isType(TokenType type) {
        return type == TokenType.INT || type == TokenType.FLOAT || type == TokenType.BOOL ||
                type == TokenType.STRING || type == TokenType.IMAGE || type == TokenType.MAT ||
                type == TokenType.PIXEL || type == TokenType.REGION;
    }

    private static Token safeGet(List<Token> tokens, int index) {
        return (index >= 0 && index < tokens.size()) ? tokens.get(index) : null;
    }

    private static TokenType safeType(List<Token> tokens, int index) {
        Token t = safeGet(tokens, index);
        return (t != null) ? t.type() : null;
    }
}